const DEFAULT_ROWS_PER_PAGE_OPTIONS = [10, 25, 50, 100];
const SINGLE_PAGE_OPTION = [10];
const TABLE_PAGINATION_HEIGHT = 52;
const TABLE_CONTAINER_MIN_HEIGHT = 50;
const TABLE_BOTTOM_PADDING = 24;
export {
  SINGLE_PAGE_OPTION,
  TABLE_BOTTOM_PADDING,
  TABLE_PAGINATION_HEIGHT,
  TABLE_CONTAINER_MIN_HEIGHT,
  DEFAULT_ROWS_PER_PAGE_OPTIONS,
};
